### ISSUE TITLE
Geoalchemy2 doesn't work well with Alembic's auto-generated migrations feature

### ISSUE THREAD

**Issue by edsinclair** [geoalchemy/geoalchemy#43]
Geoalchemy2 doesn't work well with Alembic's autogenerated migration because it creates spatial\_indexes by default
and doesn't add those indexes to the SQLAlchemy schema object:

https://github.com/geoalchemy/geoalchemy2/blob/67da25751026ab86fa288777261f2220db0ac0c6/geoalchemy2/types.py#L67-L96

It isn't so much the default creation of them as it is that it creates them by executing raw SQL:
https://github.com/geoalchemy/geoalchemy2/blob/67da25751026ab86fa288777261f2220db0ac0c6/geoalchemy2/__init__.py#L88-L93

And doesn't add the index to the SQLAlchemy schema metadata object. Alembic's autogeneration of migrations
depends on the presence of indexes in the schema object so that it can diff the model/column code against the db schema:

https://github.com/zzzeek/alembic/blob/6d69285f3833b1bdb1d0005756ffcdcad97502f1/alembic/autogenerate/compare.py#L1
https://github.com/zzzeek/alembic/blob/6d69285f3833b1bdb1d0005756ffcdcad97502f1/alembic/autogenerate/compare.py#L147

Because of this, all of Alembic's auto-generated migrations will contain a migration to remove all of the spatial\_indexes that
were automatically created by the models with Geometry columns :(

As a workaround we are declaring `Geometry` columns with `spatial_index=False` and then creating the index via a
`__table_args__` function:

```
footprint_geometry = Column(
    # Alembic doesn't know about the autogenerated spatial_index.
    # Set it false here and create it in __table_args__
    Geometry(geometry_type='GEOMETRY', srid=SRID, spatial_index=False),
    doc='The footprint of the structure'
)
```

```
@declared_attr
def __table_args__(cls):
    return (Index(
        'idx_{}_footprint_geometry'.format(cls.__tablename__), 'footprint_geometry', postgres_using='gist'
    ))
```

**Comment by ALenfant** [comment]
I agree that this is a very annoying issue, I would be glad to see it fixed

**Comment by elemoine** [comment]
This issue is to be created in https://github.com/geoalchemy/geoalchemy2.

**Comment by edsinclair** [comment]
@elemoine ah apologies for creating the issue in the wrong project. I will create this issue there. Thanks.

**Comment by edsinclair** [comment]
And I just noticed that there is already an open pull request seeking to address this issue:
https://github.com/geoalchemy/geoalchemy2/pull/81

Will watch that for updates.
